### ISSUE TITLE
Implement advanced searching

### ISSUE THREAD

**Issue by jonearley** [mlibrary/search#106]
**Creating the components**
- [x] Create a data range filter. #66
- [x] Create a nested scoping filter. #75 
- [x] Create a multiple selection filter. #65
- [x] Create a checkbox filter. #107

**Designs**
https://projects.invisionapp.com/d/main#/console/9866766/234024579/preview

**Comment by jonearley** [comment]
Created to group and track tasks / user-stories to complete implementation of advanced searching.

**Comment by varnum** [comment]
Is this ready for review without the nested scoping filter?

**Comment by jonearley** [comment]
Yes, the checked tasks are ready for review.

**Comment by varnum** [comment]
The 3 completed tasks -- #66, #65, and #107 -- are done. That leaves just #75 to go. Removing Ready for Review, re-adding Ready to Implement.

**Comment by varnum** [comment]
With #75 done, this is done.
