### ISSUE TITLE
Performance is poor.

### ISSUE THREAD

**Issue by jonearley** [mlibrary/search#110]
An audit by Chrome rates performance 16/100.

![capture](https://user-images.githubusercontent.com/1678665/30748219-9c6a3a54-9f7d-11e7-9d50-af4f7d66d660.PNG)

**Tasks**
- [x] Add filters as a batch
- [ ] Add records as a batch
- [ ] Add fields as a batch
- [ ] Look into other areas for performance improvements
- [ ] compress (gzip) spectrum requests once we are in staging/production environment.

**Comment by varnum** [comment]
What is your sense of the time (back-of-envelope estimate) investigating the causes will take?

**Comment by jonearley** [comment]
Everytime a record, filter, holding, field, or anything stored in application state is loaded in, the front end has to see if the UI should also be updated. DOM updates are the most costly. What I think I need to do is instead of adding one filter, field, record, and so on at a time is look for ways to add those in batches.

Add field, check and update UI, add field, check and update UI...

vs.

Add all fields, check and update UI.

Back of envelope estimate this would take two weeks of focused time. Or longer if for some other unknown reason performance is poor.

**Comment by jonearley** [comment]
<img width="722" alt="screen shot 2017-09-22 at 3 45 15 pm" src="https://user-images.githubusercontent.com/1678665/30761692-25238e52-9fad-11e7-8d49-853ddd30ade5.png">

@bertrama Running Chrome's audit tools. Would it make sense for to compress Spectrum requests?

**Comment by jonearley** [comment]
The application was freezing as it loaded thousands of filters one at a time. Commit 044d92c7f57742378ec8b8a05183b654df05c519 loads them all at once, fixing that problem.

**Comment by bertrama** [comment]
@jonearley Getting api responses gzipped might require changes to the apache configuration; we'd have to work with A&E for that.  Since we're using a bastardized configuration in development right now, I'd rather wait until we have a staging environment and work on it there.

**Comment by jonearley** [comment]
@bertrama waiting until we have a staging environment makes sense.

**Comment by jonearley** [comment]
Closing. This issue is covered in #104.
