### ISSUE TITLE
Implement full records closer to designs

### ISSUE THREAD

**Issue by jonearley** [mlibrary/search#139]
**Tasks**
- [ ] Move access links above record info
- [ ] Move access items into a table to match holdings
- [ ] Add "Record Info" heading.

**Comment by bertrama** [comment]
Moved to SEARCH-69.
