### ISSUE TITLE
As an advanced user, I want to see the full MARC record for a catalog item in the search interface so I can laugh at its cruddy encapsulation of cataloging data.

### ISSUE THREAD

**Issue by varnum** [mlibrary/search#46]
In the full view, a user can access the MARC record for that item
https://docs.google.com/document/d/16e4tU6rPuc--wvToz-JEBnDwckHl9Lm_8sb0PJpceyc/edit#heading=h.s8cn5nzb8pja

For full launch, present MARC data in the interface.

**Tasks**
- [x] @Treevore Provide final designs.
- [ ] @bertrama Ensure MARC is provided to the front end. 
- [ ] @jonearley Implement the designs.

**Comment by varnum** [comment]
@Treevore Do you have mockups of the MARC view for search? If/when you do, please include them here.

**Comment by Treevore** [comment]
I don't have a mockup yet, but I will work on one now. The MARC view will reveal itself below the record "card". This way you can view both the record info and source MARC with just scrolling.

That's how I was initially picturing it in my head, open to suggestions.

**Comment by jonearley** [comment]
Added tasks and @bertrama as an assignee for providing the MARC data.

**Comment by Treevore** [comment]
Here's an interactive example I mockup up today. https://invis.io/FXDNGXP6D

Basically using the same design for the bib info. Styling for the table itself (colors of striping) will change, just wanted to get something up there.

**Comment by bertrama** [comment]
SEARCH-43.
