### ISSUE TITLE
As a librarian, I want users to be limited to their institution, so that they are scoped by default to our materials.

### ISSUE THREAD

**Issue by varnum** [mlibrary/search#49]
**Context**
When a user is at the catalog landing page (not searching), they should be able to select what institution they want to be filtered to. [Related specs document](https://docs.google.com/document/d/16e4tU6rPuc--wvToz-JEBnDwckHl9Lm_8sb0PJpceyc/edit#heading=h.gje644y42s82).

**Tasks**
- [x] @Treevore Finalize institution selection designs and share them here.
- [x] @bertrama Figure out a way to pass a user's default institution to the front-end.
- [x] @jonearley Create custom landing page institution filter selection UI for the catalog datastore.
- [x] @jonearley Make it so that an institution is sticky to a user in the UI, unless they manually change it.
- [x] @jonearley Have the catalog advanced narrow search to widget use the active institution state.

**Supporting evidence**
?

**Success criteria**
When all tasks are complete.

**Comment by jonearley** [comment]
I've edited this issue heavily so it's in a user-story format.

**Comment by jonearley** [comment]
@Treevore Do you have designs to use for implementation of this feature? I think I've seen some iterations, but not sure what one was decided on to use.

**Comment by bertrama** [comment]
[I have IP ranges I can use for Ann Arbor and Flint campuses](http://its.umich.edu/enterprise/wifi-networks/core-network/network-addresses).

@varnum If detecting Clements or Bentley is required, our respective stakeholders will have to tell us what their IP ranges are.

**Comment by varnum** [comment]
I don't think that's necessary if there's ultimately a URL that can be shared that includes the "institution" (like inst=bentley, inst=clements, etc.) as in current Mirlyn.

**Comment by bertrama** [comment]
The latest version of Pride is injecting the default institution into Pride.settings i.e. `Pride.Settings.default_institution`

**Comment by jonearley** [comment]
I have a version of this up now in the UI for testing:

- The landing page institution selection visual design is not yet implemented. Visual designs on InVision: https://projects.invisionapp.com/d/main#/console/9866766/252374405/preview.
- I've placed the Institution Filter in with the rest of result filters as a dropdown. **Feedback welcome on this**.
- The default is set to U-M Ann Arbor Libraries no matter where you are, this will be hooked into the _real_ default location part soon. So ignore that.
- Sharing this earlier with @varnum, he expected links in records (such as contributors) to link to a search maintaining the same Institution Filter state, but the UI currently resets to the user's default (ex U-M Ann Arbor Libraries) regardless of what previous Institution Filter they manually selected. **Is this problematic?**

Please test the Institution Filter and comment here if you anything breaks or is unexpected.

**Comment by varnum** [comment]
I think it is problematic. If you’re a user who has set your scope to Flint, or Bentley, getting kicked out through a link in a record to other works by the same author feels wrong. Current Mirlyn preserves scope; I think changing that behavior for users who want a narrower scope (Flint, Bentley, Clements) is counterintuitive.

**Comment by varnum** [comment]
At the moment, institution=all Ann Arbor libraries is returning 0 results:
https://search-staging.www.lib.umich.edu/catalog?query=Smith&filter.institution=U-M+Ann+Arbor+Libraries

**Comment by Treevore** [comment]
Just going to reference Jon's implementation. I think the previous one being placed within the other filters was ok, this one feels better. 

<img width="405" alt="library search filter" src="https://user-images.githubusercontent.com/502199/32019214-7b307c04-b99a-11e7-96c5-d80feb7739ff.png">

**Comment by jonearley** [comment]
Sharing an in progress update for feedback. I still need to make a few more parts sticky: record field links, pagination, sorting, advanced search narrow search to filter, but everything else should behave sticky and as expected. Let me know if it doesn’t. The library filter will default to your location now too (thanks, @bertrama).

https://search-staging.www.lib.umich.edu/catalog

**Comment by jonearley** [comment]
The library filter is sticky now. Now just need to work on having it play nice with the narrow your search filter in advanced search.

**Comment by jonearley** [comment]
https://search-staging.www.lib.umich.edu/

You can find the most recent updates on: https://search-staging.www.lib.umich.edu/. I reused the institution filter from the search results page for the landing page as it was easiest solution while I got the functionality right. Perhaps this is good enough (@Treevore, @varnum) for now?

**Comment by varnum** [comment]
I’d really like to have @Treevore’s designs for the campus beta; the current one is functional, but on the landing page looks like an afterthought, and I’d like our campus partners to know we’ve been thinking of them. Of all the places polish might be needed, this feels to me like the biggest bang for the buck.

**Comment by jonearley** [comment]
@varnum Sounds good. I might add radio buttons to the design to make it accessible in a quick way.

**Comment by jonearley** [comment]
![screenshot-search-staging www lib umich edu 2017-10-26 17-00-19-595](https://user-images.githubusercontent.com/1678665/32076795-2e304bf2-ba6f-11e7-9826-5afb808c59aa.png)

https://search-staging.www.lib.umich.edu/catalog

**Comment by jonearley** [comment]
Found a bug when changing library during a search. Looking into it.

**Comment by jonearley** [comment]
Fixed.

Ready for you review, @varnum.

**Comment by varnum** [comment]
Looks like it's working well -- no bugs found.
