### ISSUE TITLE
As a new user, I want to understand what datastores are about, so that I get an idea where to begin.

### ISSUE THREAD

**Issue by varnum** [mlibrary/search#50]
**Context**
Before a user beings a search we want to provide "landing page" content so the user can get an idea about what each datastore is about and what type of resources they can expect in their results. 

**Tasks**
- [x] @bnhowell Finalize landing page text for all datastores. [Related Google Doc](https://docs.google.com/document/d/1N5q_6NfCRlnlZHLoj4ApSzh6IzT6xzWa3sTfYBwrEZc/edit#heading=h.2zbhkrrhdvss).
- [x] @Treevore Finalize landing page designs.
- [x] @jonearley Add landing page text.
- [x] @jonearley Add landing page icons.

**Success criteria**
When all of the tasks are complete.

**Comment by bnhowell** [comment]
Catalog datastore with Institutional filter selection and Access to Mirlyn Classic. 
![catalog landing page](https://user-images.githubusercontent.com/16804543/29926603-e8011a26-8e31-11e7-956e-07b377ba5795.png)
or
![catalog landing page v 2](https://user-images.githubusercontent.com/16804543/29927107-582dfed0-8e33-11e7-8dd8-59ecc3f51d0d.png)

**Comment by varnum** [comment]
I like v2 better. Though I think  the icons should match the format icons in the catalog, though.

**Comment by Treevore** [comment]
I'll update the icons to match current format icons. I like v2 as well but for catalog, it creates a lot of stacked content. Going to try another version for the location picker outlier. I think the mirlyn classic link is great. tempted to make it a 6px font just to be rude to those classic folks ;)

I'll upload an invision link of all landing pages.

**Comment by jonearley** [comment]
Are the screenshots @bnhowell what should be developed? I don't see them in Invision. Wondering what iteration I should be referencing.

**Comment by Treevore** [comment]
https://projects.invisionapp.com/d/main#/console/9866766/252374406/inspect Here's the invision upload, all landing pages should be available.

**Comment by jonearley** [comment]
I'm scoping this issue to be just about landing page icons and text content. I will open another issue about the catalog specific peices.

**Comment by jonearley** [comment]
Updated: added landing page text, but still need to add icons.

**Comment by jonearley** [comment]
Thanks for providing designs @Treevore. I just need finalization on the text to use.

**Comment by jonearley** [comment]
Added Google Doc that is the source of the help text to @bnhowell's task.

**Comment by bnhowell** [comment]
All datastore summaries look like they were vetted except the articles summary:

**Landing Page Description**
Articles is a gateway to discovering a wide variety of library resources. 

@heidisb stated, "this is not good" in the [related google doc ](https://docs.google.com/a/umich.edu/document/d/1N5q_6NfCRlnlZHLoj4ApSzh6IzT6xzWa3sTfYBwrEZc/edit?usp=sharing)

Your results will include scholarly journal articles, newspaper articles, book chapters, conference proceedings, and more. 

**Results page help text**
Articles Results: Scholarly journal articles, newspaper articles, book chapters, conference proceedings, and more.

**Comment by heidisb** [comment]
I add some comments and suggestion in the document.

**Comment by jonearley** [comment]
Thanks! Once I get the go for final copy (from @bnhowell?) I will add it.

**Comment by bnhowell** [comment]
Looks good everyone. Thank you for your feedback.

Let's implement the text on the [related Google document](https://docs.google.com/document/d/1N5q_6NfCRlnlZHLoj4ApSzh6IzT6xzWa3sTfYBwrEZc/edit?ts=59b8135d)

**Comment by jonearley** [comment]
Updated descriptions to match what is in the document.

**Comment by jonearley** [comment]
Added icons.

**Comment by varnum** [comment]
Lovely.
