### ISSUE TITLE
Add Ask a Librarian widget to search interface

### ISSUE THREAD

**Issue by varnum** [mlibrary/search#53]
**Tasks**
- [x] @bnhowell, @Treevore Provide designs.
- [x] @jonearley Add button in nav to pop open the ask a librarian service
- [x] @bertrama Setup EZProxy for libraryh3lp presence api: http://libraryh3lp.com/presence/jid/umlibraryaskalibrarian/chat.libraryh3lp.com/text
https://libraryh3lp-com.proxy.lib.umich.edu/presence/jid/umlibraryaskalibrarian/chat.libraryh3lp.com/text
- [x] @jonearley Add icon connected to the libraryh3lp api to indicate online or offline when proxy is setup

**Comment by varnum** [comment]
NOTE:  Pending confirmation from Meghan Sitar.

**Comment by varnum** [comment]
Confirmation from Megan Sitar, who manages Ask a Librarian, that this is OK:


> Yes, completely comfortable with that. Our strategy will be to submit the feedback on the user's 
> behalf through the feedback link rather than asking them to restate what they tell us. I appreciate 
> you checking.
> 
> 
> 
> Thanks,
> Meghan
> 
> 
>

**Comment by jonearley** [comment]
![screenshot-projects invisionapp com 2017-09-08 10-47-32](https://user-images.githubusercontent.com/1678665/30217116-2832a39c-9483-11e7-9f3d-cfb404f54877.png)

[Ask a Librarian designs on Invision](https://projects.invisionapp.com/d/main#/console/11972281/252368258/preview)

**Comment by jonearley** [comment]
777dd7609577cfd07dac3ae04c6555485a2ba70b: Added the link to the header.

But I need to still add in the chat icon and consider the available and unavailable states of the service. @bnhowell could your designs be updated to include these two states (available and unavailable)?

**Comment by jonearley** [comment]
I don't have this icon as an SVG, so I used a similar Google icon set option. I can update when provided with an SVG.

**Comment by jonearley** [comment]
Updated issue with tasks.

**Comment by Treevore** [comment]
<img width="384" alt="screen shot 2017-09-15 at 1 06 34 pm" src="https://user-images.githubusercontent.com/502199/30494601-d06b350e-9a16-11e7-812e-54cf69fd8f2e.png">

Here are some icons from the material design set. Started with the offline being the comment with X through, but provided an outline alternative. Does anyone think the circle would be a better alternative? I see that pattern in a lot of chat clients (slack, hangouts, etc)

Here are the svg's used. (note I flipped them horizontally)
[AskALibrarianIcons.zip](https://github.com/mlibrary/search/files/1307115/AskALibrarianIcons.zip)

**Comment by varnum** [comment]
I like the "x" and green fill for not availalble/available.  Though, if we follow the suggestions at today's search meeting, this becomes the "floaty" icon in the lower right, and the top-right becomes "Get Help".

**Comment by bnhowell** [comment]
I'll update these icons tomorrow with the chat icon Trevor has above. Just wanted to show interactions with different icon sets (available/unavailable) states. 
https://invis.io/KMDE2X8WA

**Comment by bertrama** [comment]
Proxied urls for library h3lp:

https://login.proxy.lib.umich.edu/login?url=https://libraryh3lp.com/presence/jid/umlibraryaskalibrarian/chat.libraryh3lp.com/text

or 

https://login.proxy.lib.umich.edu/login?url=https://libraryh3lp.com/presence/jid/umlibraryaskalibrarian/chat.libraryh3lp.com/js

**Comment by jonearley** [comment]
@varnum ready for your review.

**Comment by varnum** [comment]
Icon looks great, though I thought we decided on a different placement:

1. Get Help (linking to https://www.lib.umich.edu/get-research-help in the header
2. Ask a Librarian pop-up (as with www.lib) in the lower right
3. Give Feedback then moves to  the right side

@heidisb @bnhowell

**Comment by heidisb** [comment]
That synopsis is my understanding as well.

**Comment by varnum** [comment]
I see the problem -- we have two tickets: this, and #98

**Comment by varnum** [comment]
See #132 for additional work to move Ask into the lower right of the page. Work on this issue is done.
