### ISSUE TITLE
As a user, I want to search online journals by specific fields

### ISSUE THREAD

**Issue by varnum** [mlibrary/search#72]
Fields available in https://earleyj-drupal8.www.lib.umich.edu/onlinejournals/advanced should include what is currently on https://www.lib.umich.edu/searchtools#journals/search

See spec at https://docs.google.com/document/d/16e4tU6rPuc--wvToz-JEBnDwckHl9Lm_8sb0PJpceyc/edit#heading=h.qx8b0tggkgnk

**Tasks**
- [x] @bertrama Ensure all journal fields are available to the UI
Currently missing: 
    - [x] Title Starts With
    - [x] [ISSN](https://earleyj-drupal8.www.lib.umich.edu/onlinejournals?query=isn%3A00280836)

- [x] @jonearley Ensure all journal fields are configured to be available in the UI
- [x] @varnum Review and QA test to make sure these work as expected.

More detailed tracking of this progress:
https://tools.lib.umich.edu/confluence/display/LDD/Fielded+Search+Requirements

**Comment by jonearley** [comment]
Not a bug. This feature is still in development. Added tasks to this user-story.

**Comment by jonearley** [comment]
Checked of tasks. Ready for review, @varnum.

**Comment by varnum** [comment]
Seeing the same oddity as I see in Databases (issue #73):  title searches bring up fewer results than title_starts_with searches. @bertrama

**Comment by varnum** [comment]
Fix for #73 resolved this, too. Closing.
