### ISSUE TITLE
As an advanced user, I want to limit my catalog search to a specific library and associated collection so that I can search just the materials I think are relevant

### ISSUE THREAD

**Issue by varnum** [mlibrary/search#75]
The catalog advanced search interface should allow a user to pick an institution, location at that institution, and/or collection within than location to narrow the search scope. 
https://mirlyn.lib.umich.edu/Search/Advanced

Spec: https://docs.google.com/document/d/16e4tU6rPuc--wvToz-JEBnDwckHl9Lm_8sb0PJpceyc/edit#heading=h.26ck4f9g63fi

**Designs**
<img width="332" alt="screen shot 2017-09-14 at 10 44 12 am" src="https://user-images.githubusercontent.com/1678665/30436368-f4000374-9939-11e7-81fc-af3a6a334dc8.png">

**Tasks**
- [x] @varnum Develop specifications for where the hierarchical data on Institution / Location / Collection lives. 
- [x] @bertrama Provide or show how to access this Institution -> Location -> Collection nested data.
- [x] @jonearley Add filter to catalog advanced search.
- [x] @bertrama Accept search values on the back end.

**Comment by varnum** [comment]
Tim Prettyman says:

> The two config files are instLocs.yaml and locColl.yaml in the conf directory.  They 
> get parsed by services/Search/Advanced.php, and are used to generate the 
> display in the smarty template interface/themes/um/Search/advanced.tpl
> 
> It's all rather ugly--my apologies.
> 
> -Tim

@bertrama

**Comment by varnum** [comment]
Related to #49

**Comment by bertrama** [comment]
@jonearley I have some preliminary implementations with a new attribute named hierarchy.

```javascript
Pride.AllDatastores.get(dsUid).get('hierarchy')
```

**Comment by varnum** [comment]
@jonearley I'm not seeing the institution-library-collection filter in Advanced search. Should I?

**Comment by jonearley** [comment]
@varnum, no not yet. I started working on this unique widget yesterday tho.

**Comment by jonearley** [comment]
A version is up, but not quite ready for review. Need to tweak how I generate the filtered search.

**Comment by bertrama** [comment]
The back end should be applying these three filters as appropriate.

**Comment by bertrama** [comment]
Earlier problems with Flint as an institution, reported by @jonearley have been fixed.
This is ready for general review.

**Comment by varnum** [comment]
Working nicely. Done!
