### ISSUE TITLE
As a user, I want to know the date range of each volume of physical holdings for a serial so I can request the right one

### ISSUE THREAD

**Issue by varnum** [mlibrary/search#82]
**Initial questions**
For physical journals in the stacks, coverage is being displayed as a multi-digit number that doesn't correspond obviously to a date range. For example, see the horrendous Coverage data for Nature:
https://earleyj-drupal8.www.lib.umich.edu/catalog/record/000637680

Is the correct field being used in the interface?

**Proposal**
Improve holding coverage formatting based on evidence and or confirm Mirlyn coverage formatting is a good solution.

**Supporting Evidence**
?

**Tasks**
- [ ] @varnum Put together a group to gather requirements, identify what information is needed, why it is needed, and where that information lives.
- [ ] Decide what holding coverage format to display (@heidisb, @varnum )? Do we even have the option to choose or are we limited by metadata (@bertrama)?
- [ ] @bertrama Update holding format to decided format.
- [ ] @jonearley Make sure format is configure to be displayed in the UI.
- [ ] @varnum Review.

**Comment by varnum** [comment]
A related (?) problem: we are displaying only a volume number, with no context, in several cases:
https://earleyj-drupal8.www.lib.umich.edu/catalog/record/006871228
https://earleyj-drupal8.www.lib.umich.edu/catalog/record/011728394

**Comment by jonearley** [comment]
Pulling @bertrama into this as the backend is fetching this data.

An example of a holding being display in the beta and then Mirlyn. I think this is what @varnum is referring to:

Beta coverage format: 5057481
![screen shot 2017-09-13 at 10 31 31 am](https://user-images.githubusercontent.com/1678665/30383064-c67e0926-986e-11e7-8445-c2bdc35d517c.png)

Mirlyn coverage format: v.505:no.7481(2014:Jan. 02)
![screen shot 2017-09-13 at 10 31 44 am](https://user-images.githubusercontent.com/1678665/30383063-c60cc716-986e-11e7-8fe2-37f22dacbcbd.png)

Also, do we have any evidence for what format holding coverage format is most useful to users? @bnhowell @heidisb

**Comment by jonearley** [comment]
Updated user-story and added tasks.

**Comment by varnum** [comment]
A user who wants something pulled from remote shelving and delivered to them would be working from a citation. They would likely have either the volume/issue, or the date range so that they can request the right item. Seeing each holding with the volume/issue and date, as Mirlyn displays, enables them to efficiently request the specific volume from a multivolume serial that they might want.

**Comment by varnum** [comment]
We're definitely limited by MARC data, but we should be displaying what we have.

**Comment by varnum** [comment]
I think there are two issues in this ticket

First, the upper part of the screen shot Jon provided, we are not properly displaying volume/issue/date information for specific items on the holdings record. This information is attached individually to each holding. 

Second, the lower part, we are not displaying summary holdings information. This is related to the entire catalog record and describes in free text the range of dates/volumes the library has, even if the items are not catalogued individually. They indicate to the user that more may be available than on the individual lines.

**Comment by heidisb** [comment]
If there are two issues we should split it into two user stories. And I agree with Albert that it is too late in the dev cycle to be diving into this granular of a spec. The launch is a beta and there's going to be things like this that we have to let not be ready. 

And what @varnum said about the coverage format, @jonearley.  The most typical scenario will be working off a citation, so it's really dependent on however that publication is serialized (is that a word!?).

**Comment by varnum** [comment]
There is already an issue for the summary holdings statement: #100 

For this issue, it looks like the interface is dropping letters and punctuation from the item holdings description in Aleph. 
On https://earleyj-drupal8.www.lib.umich.edu/catalog/record/011728394, coverage is shown as `1`, `2`, etc. In the MARC record, it the 974$z shows `v.1`, `v.2`, etc.

It looks like on serials records, only the first part of the 974$z is being displayed. On https://earleyj-drupal8.www.lib.umich.edu/catalog/record/000637680, we see `v.117` where in the MARC that field contains `v.117 1926 Jan-Jun`

**Comment by jonearley** [comment]
Sorry I missed this at first, but the holding API is sending me a field called 'description' that seems to be what is used in Mirlyn's holding display. I made an update and they should match now.

**Comment by jonearley** [comment]
If interested, this is the API holding request for that record: https://earleyj-drupal8.www.lib.umich.edu/testapp/spectrum/mirlyn/holdings/000637680.

**Comment by jonearley** [comment]
It's possible this issue could be closed now with review, @varnum.

**Comment by varnum** [comment]
I think so -- that fix solves all the specific records with odd displays noted in this issue.

Yay!

**Comment by varnum** [comment]
Done. Closed relevant Jira tickets.
