### ISSUE TITLE
Should we have basic search syntax documentation for users?

### ISSUE THREAD

**Issue by jonearley** [mlibrary/search#88]
Should we provide documentation describing how the syntax of the basic search box works and make that available to the user?

An example of how GitHub documents how to search with their syntax:
https://help.github.com/articles/searching-issues-and-pull-requests/
It would be easy for me to add a static page like this.

**Evidence**
From @bnhowell's testing, often users want to know how their search term is being interpreted by the system. This is one simple proposal to solve that problem. The more complicated one would be syntax highlighting (takes more development time), but documentation could supplement syntax highlighting either way.

**Tasks**
- [x] @varnum Write text
- [x] @bnhowell and @Treevore Where does link to search help go in interface? Need designs
- [x] @jonearley Create static page with search help content
- [x] @jonearley Implement design

**Comment by varnum** [comment]
Yes, I think we should have some basic help. Ideally for the public beta, but definitely for the launch. I can take a stab at drafting something.

**Comment by heidisb** [comment]
Yes. Basic. Happy to look at whatever you come up with @varnum .

**Comment by varnum** [comment]
OK, @heidisb -- I've drafted something here:
https://docs.google.com/document/d/1sygaPOQISEWa6zywRDFFcZmEILo84gSdzQ7QamS18Ew/edit#heading=h.ho3l6wuvrvjs

Too much? Too little? All wrong? Let me know.

**Comment by heidisb** [comment]
Close to just right in terms of what's covered. Did a bit of wordsmithing and breaking up content. Caught things that were missing.

**Comment by varnum** [comment]
Thanks, Heidi! Appreciate your word-smithing as always.

Any other comments or suggestions before we mark this as "ready to implement"?

**Comment by varnum** [comment]
The text seems good. We need a place to link this page from. Assigning @Treevore and @bnhowell, and adding some to-do items and assigning them to you. CC @jonearley

**Comment by heidisb** [comment]
Welp. I assume this means we need to either put the Help *back* in the footer, or consider if there is a place with better proximity to the search box that would be appropriate.

**Comment by bnhowell** [comment]
Three options: 

[Help link in main nav.pdf](https://github.com/mlibrary/search/files/1319279/Help.link.in.main.nav.pdf)

[Help link in Everything Search Results (No Results in any data store) v.2.pdf](https://github.com/mlibrary/search/files/1319281/Help.link.in.Everything.Search.Results.No.Results.in.any.data.store.v.2.pdf)

[Help link in footer.pdf](https://github.com/mlibrary/search/files/1319280/Help.link.in.footer.pdf)

**Comment by heidisb** [comment]
I like the parallelism of the language in the header. It should probably be
more persistent than only when you get no results on Everything. And in the
footer seems too hidden to me.

-hsb

---
Heidi Steiner Burkhardt | User Experience Specialist | University of
Michigan Library
heidisb@umich.edu | 734.615.6130 | @heidi_sb

**Comment by varnum** [comment]
I'm with @heidisb -- it will be useful all the time, not only when a search has failed to retrieve something, and when a long results list pushes the footer off the screen. 

I prefer top right.

**Comment by varnum** [comment]
I think we are ready to implement. @heidisb @bnhowell ?

**Comment by heidisb** [comment]
SHIP IT. Top right.

**Comment by jonearley** [comment]
I've added this page and made some changes to the content.

- Some content was written as asking users to look in a certain direction, but that type of copy is not great for accessible. Avoid language such as "To the right you will see...".
- Added links to appropriate terms.

https://search-staging.www.lib.umich.edu/how-to-use-search

Preview:

![search-staging www lib umich edu-how-to-use-search](https://user-images.githubusercontent.com/1678665/31733168-d7e104b0-b408-11e7-9661-047d1c16ff2f.png)

**Comment by varnum** [comment]
I added a "get more help" header and sentence at the end, in the Word doc, earlier today.

How do I get more help?
You can contact [Ask a Librarian](https://www.lib.umich.edu/get-research-help) by email, chat, or phone.

**Comment by jonearley** [comment]
I recommend we don't repeat content and add generic help links on this page. Generic help will soon be in the main header (based on conversations at our last check-in, related: #98). We should rely on that prominent placement for users to get access to help.

**Comment by heidisb** [comment]
This looks great, Jon. And good call on your edits...I should've caught
that. I also agree that we don't need to have an additional prompt for how
to get help in the text of this page when we're already featuring it
prominently.

-hsb

---
Heidi Steiner Burkhardt | User Experience Specialist | University of
Michigan Library
heidisb@umich.edu | 734.615.6130 | @heidi_sb

**Comment by varnum** [comment]
Agreed-- I like the way you've organized the examples. Looks great!
